Add database
ciiska5/java-filmorate pull request #7
Opened 2023-05-10 22:50 UTC by ciiska5

Добавление работы приложения с БД

2023-05-11 02:26 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "LEFT JOIN genres AS g ON fg.genre_id = g.genre_id " +
Здорово, что жанр вытаскивается вместе с фильмом в одном запросе.
Точно ли бывает фильм без жанра?

2023-05-11 02:30 UTC, EvgenyKoptubenko commented
InMemoryUserStorage - есть дублирование кода

if (!ifUser && !ifFriend) {
                log.error("Пользователи не найдены");
                throw new UserNotFoundException("Пользователи не найдены");
            } else if (!ifUser) {
                log.error("Пользователь с id = {} не найден", userId);
                throw new UserNotFoundException(String.format("Пользователь с id = %d не найден", userId));
            }
            log.error("Пользователь с id = {} не найден", friendId);
            throw new UserNotFoundException(String.format("Пользователь с id = %d не найден", friendId));

2023-05-11 02:31 UTC, EvgenyKoptubenko commented
Если отправить неверный запрос, то приходит верное сообщение об ошибке, что запрос неверный. Только это должен быть ответ BadRequest, а не 500
curl --request POST \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name2":"nameItem",
	"email":"email3email.com",
  "login":"login"
}'

2023-05-11 02:32 UTC, EvgenyKoptubenko commented
Попробуй сделать так, чтобы в сообщении об ошибке было написано какое поле прислали неверное
curl --request PUT \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"id":1,
	"name":"nameItem",
	"email":"wrong_emailmail.com",
  "login":"login22",
	"birthday":"2001-01-01"
}'

500
{
	"error": "Неверный запрос."
}

2023-05-11 02:38 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложение по улучшению кода

2023-05-11 19:25 UTC, ciiska5 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "LEFT JOIN genres AS g ON fg.genre_id = g.genre_id " +
Теоретически (и практически в тестах постмана) может быть такое, что какому-то фильму не присвоен жанр.

2023-05-14 14:51 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-05-21 07:34 UTC, merged